# Generated by Django 5.1.4 on 2024-12-12 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0002_categories_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("amount", models.PositiveIntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=24)),
                ("slug", models.SlugField(unique=True)),
                ("status", models.BooleanField(default=True)),
                ("image_url", models.URLField(max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.categories",
                    ),
                ),
            ],
            options={
                "verbose_name": "produto",
                "verbose_name_plural": "produtos",
                "ordering": ["created_at"],
            },
        ),
    ]
