# Generated by Django 5.1.4 on 2024-12-29 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_alter_categories_status"),
        ("products", "0002_product_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="amount",
            field=models.PositiveIntegerField(default=0, verbose_name="Quantidade"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.categories",
                verbose_name="Categoria a qual o produto pertence",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=24, verbose_name="Preço"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.BooleanField(
                default=True, verbose_name="Dispnível ou indisponível"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário que cadstrou",
            ),
        ),
    ]
