# Generated by Django 5.1.4 on 2025-01-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="complement",
            field=models.CharField(max_length=255, verbose_name="Complemento"),
        ),
    ]
