# Generated by Django 5.1.4 on 2025-01-07 13:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shopping", "0004_shopping_cancelled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CTC", "credit_card"),
                            ("BKS", "bank_slip"),
                            ("PIX", "pix"),
                        ],
                        db_default="PIX",
                        help_text="Devem ser CTC = Cartão de crédito, BKS = Boleto bancário ou PIX = Pix",
                        max_length=3,
                        verbose_name="Forma de pagamento",
                    ),
                ),
                (
                    "divided_into",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Dividido em quantas vezes"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=24, verbose_name="Valor parcial"
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=24, verbose_name="Valor total"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shopping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopping.shopping",
                        verbose_name="Categoria a qual o produto pertence",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário que cadstrou",
                    ),
                ),
            ],
            options={
                "verbose_name": "pagamento",
                "verbose_name_plural": "pagamentos",
                "ordering": ["created_at"],
            },
        ),
    ]
