# Generated by Django 5.1.4 on 2025-01-16 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
        ("shopping", "0006_shopping_shipping_value_shopping_value"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="shopping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shopping.shopping",
                verbose_name="Compra a qual o pagamento é referente",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário que está pagando",
            ),
        ),
    ]
