# Generated by Django 5.1.4 on 2024-12-29 13:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_amount_alter_product_category_and_more"),
        ("shopping_cart", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shoppingcart",
            unique_together={("user", "product")},
        ),
    ]
