# Generated by Django 5.1.4 on 2024-12-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopping",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
    ]
