# Generated by Django 5.1.4 on 2024-12-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0002_alter_shopping_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopping",
            name="payment_status",
            field=models.BooleanField(
                default=False, verbose_name="Pagamento pendente ou finalizado"
            ),
        ),
        migrations.AlterField(
            model_name="shopping",
            name="quantity_products",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Quantidade de produtos"
            ),
        ),
        migrations.AlterField(
            model_name="shopping",
            name="status",
            field=models.BooleanField(
                default=True, verbose_name="Finalizada ou em aberto"
            ),
        ),
    ]
