# Generated by Django 5.1.4 on 2025-01-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0003_alter_shopping_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopping",
            name="cancelled",
            field=models.BooleanField(default=False, verbose_name="Cancelada ou não"),
        ),
    ]
