# Generated by Django 5.1.4 on 2025-01-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_alter_address_complement"),
        ("shopping", "0004_shopping_cancelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopping",
            name="address",
            field=models.ForeignKey(
                default="321734ff-0dae-43c7-89c9-5108d38ef6aa",
                on_delete=django.db.models.deletion.CASCADE,
                to="address.address",
                verbose_name="Endereço",
            ),
            preserve_default=False,
        ),
    ]
